// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: actions.proto

package save

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_ActionNewRoadRequested           ActionType = 0
	ActionType_ActionNewSettlementRequested     ActionType = 1
	ActionType_ActionSettlementUpgradeRequested ActionType = 2
	ActionType_ActionCameraMoved                ActionType = 3
	ActionType_ActionResearchRequested          ActionType = 4
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ActionNewRoadRequested",
		1: "ActionNewSettlementRequested",
		2: "ActionSettlementUpgradeRequested",
		3: "ActionCameraMoved",
		4: "ActionResearchRequested",
	}
	ActionType_value = map[string]int32{
		"ActionNewRoadRequested":           0,
		"ActionNewSettlementRequested":     1,
		"ActionSettlementUpgradeRequested": 2,
		"ActionCameraMoved":                3,
		"ActionResearchRequested":          4,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_actions_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_actions_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{0}
}

type GameReplay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Header   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Board    *Board    `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	Player   *Player   `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	Actions  []*Action `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	LastTick int64     `protobuf:"varint,5,opt,name=last_tick,json=lastTick,proto3" json:"last_tick,omitempty"`
}

func (x *GameReplay) Reset() {
	*x = GameReplay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameReplay) ProtoMessage() {}

func (x *GameReplay) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameReplay.ProtoReflect.Descriptor instead.
func (*GameReplay) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{0}
}

func (x *GameReplay) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GameReplay) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GameReplay) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *GameReplay) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *GameReplay) GetLastTick() int64 {
	if x != nil {
		return x.LastTick
	}
	return 0
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    ActionType     `protobuf:"varint,1,opt,name=type,proto3,enum=save.ActionType" json:"type,omitempty"`
	Tick    int64          `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Payload *ActionPayload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ActionNewRoadRequested
}

func (x *Action) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Action) GetPayload() *ActionPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ActionPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ActionPayload_NewRoadRequested
	//	*ActionPayload_NewSettlementRequested
	//	*ActionPayload_SettlementUpgradeRequested
	//	*ActionPayload_CameraMoved
	//	*ActionPayload_ResearchRequested
	Payload isActionPayload_Payload `protobuf_oneof:"payload"`
}

func (x *ActionPayload) Reset() {
	*x = ActionPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionPayload) ProtoMessage() {}

func (x *ActionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionPayload.ProtoReflect.Descriptor instead.
func (*ActionPayload) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{2}
}

func (m *ActionPayload) GetPayload() isActionPayload_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ActionPayload) GetNewRoadRequested() *NewRoadRequested {
	if x, ok := x.GetPayload().(*ActionPayload_NewRoadRequested); ok {
		return x.NewRoadRequested
	}
	return nil
}

func (x *ActionPayload) GetNewSettlementRequested() *NewSettlementRequested {
	if x, ok := x.GetPayload().(*ActionPayload_NewSettlementRequested); ok {
		return x.NewSettlementRequested
	}
	return nil
}

func (x *ActionPayload) GetSettlementUpgradeRequested() *SettlementUpgradeRequested {
	if x, ok := x.GetPayload().(*ActionPayload_SettlementUpgradeRequested); ok {
		return x.SettlementUpgradeRequested
	}
	return nil
}

func (x *ActionPayload) GetCameraMoved() *CameraMoved {
	if x, ok := x.GetPayload().(*ActionPayload_CameraMoved); ok {
		return x.CameraMoved
	}
	return nil
}

func (x *ActionPayload) GetResearchRequested() *ResearchRequested {
	if x, ok := x.GetPayload().(*ActionPayload_ResearchRequested); ok {
		return x.ResearchRequested
	}
	return nil
}

type isActionPayload_Payload interface {
	isActionPayload_Payload()
}

type ActionPayload_NewRoadRequested struct {
	NewRoadRequested *NewRoadRequested `protobuf:"bytes,1,opt,name=new_road_requested,json=newRoadRequested,proto3,oneof"`
}

type ActionPayload_NewSettlementRequested struct {
	NewSettlementRequested *NewSettlementRequested `protobuf:"bytes,2,opt,name=new_settlement_requested,json=newSettlementRequested,proto3,oneof"`
}

type ActionPayload_SettlementUpgradeRequested struct {
	SettlementUpgradeRequested *SettlementUpgradeRequested `protobuf:"bytes,3,opt,name=settlement_upgrade_requested,json=settlementUpgradeRequested,proto3,oneof"`
}

type ActionPayload_CameraMoved struct {
	CameraMoved *CameraMoved `protobuf:"bytes,4,opt,name=camera_moved,json=cameraMoved,proto3,oneof"`
}

type ActionPayload_ResearchRequested struct {
	ResearchRequested *ResearchRequested `protobuf:"bytes,5,opt,name=research_requested,json=researchRequested,proto3,oneof"`
}

func (*ActionPayload_NewRoadRequested) isActionPayload_Payload() {}

func (*ActionPayload_NewSettlementRequested) isActionPayload_Payload() {}

func (*ActionPayload_SettlementUpgradeRequested) isActionPayload_Payload() {}

func (*ActionPayload_CameraMoved) isActionPayload_Payload() {}

func (*ActionPayload_ResearchRequested) isActionPayload_Payload() {}

type NewRoadRequested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *NewRoadRequested) Reset() {
	*x = NewRoadRequested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewRoadRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRoadRequested) ProtoMessage() {}

func (x *NewRoadRequested) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRoadRequested.ProtoReflect.Descriptor instead.
func (*NewRoadRequested) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{3}
}

func (x *NewRoadRequested) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type NewSettlementRequested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *NewSettlementRequested) Reset() {
	*x = NewSettlementRequested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewSettlementRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSettlementRequested) ProtoMessage() {}

func (x *NewSettlementRequested) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSettlementRequested.ProtoReflect.Descriptor instead.
func (*NewSettlementRequested) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{4}
}

func (x *NewSettlementRequested) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type SettlementUpgradeRequested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SettlementId int64 `protobuf:"varint,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
}

func (x *SettlementUpgradeRequested) Reset() {
	*x = SettlementUpgradeRequested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettlementUpgradeRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementUpgradeRequested) ProtoMessage() {}

func (x *SettlementUpgradeRequested) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementUpgradeRequested.ProtoReflect.Descriptor instead.
func (*SettlementUpgradeRequested) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{5}
}

func (x *SettlementUpgradeRequested) GetSettlementId() int64 {
	if x != nil {
		return x.SettlementId
	}
	return 0
}

type CameraMoved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Delta *Vector `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
}

func (x *CameraMoved) Reset() {
	*x = CameraMoved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CameraMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraMoved) ProtoMessage() {}

func (x *CameraMoved) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraMoved.ProtoReflect.Descriptor instead.
func (*CameraMoved) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{6}
}

func (x *CameraMoved) GetDelta() *Vector {
	if x != nil {
		return x.Delta
	}
	return nil
}

type ResearchRequested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Technology TechnologyType `protobuf:"varint,1,opt,name=technology,proto3,enum=save.TechnologyType" json:"technology,omitempty"`
}

func (x *ResearchRequested) Reset() {
	*x = ResearchRequested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_actions_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResearchRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchRequested) ProtoMessage() {}

func (x *ResearchRequested) ProtoReflect() protoreflect.Message {
	mi := &file_actions_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchRequested.ProtoReflect.Descriptor instead.
func (*ResearchRequested) Descriptor() ([]byte, []int) {
	return file_actions_proto_rawDescGZIP(), []int{7}
}

func (x *ResearchRequested) GetTechnology() TechnologyType {
	if x != nil {
		return x.Technology
	}
	return TechnologyType_TechnologyMining
}

var File_actions_proto protoreflect.FileDescriptor

var file_actions_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x73, 0x61, 0x76, 0x65, 0x1a, 0x0c, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc0, 0x01, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x79, 0x12, 0x24, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x42,
	0x6f, 0x61, 0x72, 0x64, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x61,
	0x76, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x12, 0x26, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x61,
	0x73, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x22, 0x71, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x12, 0x2d, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x61,
	0x76, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xa4, 0x03, 0x0a, 0x0d, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x46, 0x0a, 0x12, 0x6e,
	0x65, 0x77, 0x5f, 0x72, 0x6f, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x4e,
	0x65, 0x77, 0x52, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x48,
	0x00, 0x52, 0x10, 0x6e, 0x65, 0x77, 0x52, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x12, 0x58, 0x0a, 0x18, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x4e, 0x65, 0x77,
	0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x16, 0x6e, 0x65, 0x77, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x64, 0x0a,
	0x1c, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x75, 0x70, 0x67, 0x72,
	0x61, 0x64, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x1a, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x0c, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f, 0x6d, 0x6f,
	0x76, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x61, 0x76, 0x65,
	0x2e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0b,
	0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x48, 0x0a, 0x12, 0x72,
	0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x11, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x3e, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x52, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x44, 0x0a, 0x16, 0x4e, 0x65, 0x77, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73,
	0x61, 0x76, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x41, 0x0a, 0x1a, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x74,
	0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x0b, 0x43, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x22, 0x49, 0x0a, 0x11,
	0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x12, 0x34, 0x0a, 0x0a, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x54, 0x65, 0x63,
	0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x74, 0x65, 0x63,
	0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2a, 0xa4, 0x01, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x65, 0x77, 0x52, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x10, 0x00, 0x12, 0x20, 0x0a, 0x1c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x65, 0x77, 0x53,
	0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x10, 0x01, 0x12, 0x24, 0x0a, 0x20, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65,
	0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x64, 0x10,
	0x03, 0x12, 0x1b, 0x0a, 0x17, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x10, 0x04, 0x42, 0x1f,
	0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x31, 0x31,
	0x30, 0x2f, 0x6b, 0x69, 0x6e, 0x67, 0x64, 0x6f, 0x6d, 0x73, 0x2f, 0x73, 0x61, 0x76, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_actions_proto_rawDescOnce sync.Once
	file_actions_proto_rawDescData = file_actions_proto_rawDesc
)

func file_actions_proto_rawDescGZIP() []byte {
	file_actions_proto_rawDescOnce.Do(func() {
		file_actions_proto_rawDescData = protoimpl.X.CompressGZIP(file_actions_proto_rawDescData)
	})
	return file_actions_proto_rawDescData
}

var file_actions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_actions_proto_goTypes = []interface{}{
	(ActionType)(0),                    // 0: save.ActionType
	(*GameReplay)(nil),                 // 1: save.GameReplay
	(*Action)(nil),                     // 2: save.Action
	(*ActionPayload)(nil),              // 3: save.ActionPayload
	(*NewRoadRequested)(nil),           // 4: save.NewRoadRequested
	(*NewSettlementRequested)(nil),     // 5: save.NewSettlementRequested
	(*SettlementUpgradeRequested)(nil), // 6: save.SettlementUpgradeRequested
	(*CameraMoved)(nil),                // 7: save.CameraMoved
	(*ResearchRequested)(nil),          // 8: save.ResearchRequested
	(*Header)(nil),                     // 9: save.Header
	(*Board)(nil),                      // 10: save.Board
	(*Player)(nil),                     // 11: save.Player
	(*Position)(nil),                   // 12: save.Position
	(*Vector)(nil),                     // 13: save.Vector
	(TechnologyType)(0),                // 14: save.TechnologyType
}
var file_actions_proto_depIdxs = []int32{
	9,  // 0: save.GameReplay.header:type_name -> save.Header
	10, // 1: save.GameReplay.board:type_name -> save.Board
	11, // 2: save.GameReplay.player:type_name -> save.Player
	2,  // 3: save.GameReplay.actions:type_name -> save.Action
	0,  // 4: save.Action.type:type_name -> save.ActionType
	3,  // 5: save.Action.payload:type_name -> save.ActionPayload
	4,  // 6: save.ActionPayload.new_road_requested:type_name -> save.NewRoadRequested
	5,  // 7: save.ActionPayload.new_settlement_requested:type_name -> save.NewSettlementRequested
	6,  // 8: save.ActionPayload.settlement_upgrade_requested:type_name -> save.SettlementUpgradeRequested
	7,  // 9: save.ActionPayload.camera_moved:type_name -> save.CameraMoved
	8,  // 10: save.ActionPayload.research_requested:type_name -> save.ResearchRequested
	12, // 11: save.NewRoadRequested.position:type_name -> save.Position
	12, // 12: save.NewSettlementRequested.position:type_name -> save.Position
	13, // 13: save.CameraMoved.delta:type_name -> save.Vector
	14, // 14: save.ResearchRequested.technology:type_name -> save.TechnologyType
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_actions_proto_init() }
func file_actions_proto_init() {
	if File_actions_proto != nil {
		return
	}
	file_schema_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_actions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameReplay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actions_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actions_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewRoadRequested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actions_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewSettlementRequested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actions_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettlementUpgradeRequested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actions_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CameraMoved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_actions_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResearchRequested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_actions_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ActionPayload_NewRoadRequested)(nil),
		(*ActionPayload_NewSettlementRequested)(nil),
		(*ActionPayload_SettlementUpgradeRequested)(nil),
		(*ActionPayload_CameraMoved)(nil),
		(*ActionPayload_ResearchRequested)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_actions_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actions_proto_goTypes,
		DependencyIndexes: file_actions_proto_depIdxs,
		EnumInfos:         file_actions_proto_enumTypes,
		MessageInfos:      file_actions_proto_msgTypes,
	}.Build()
	File_actions_proto = out.File
	file_actions_proto_rawDesc = nil
	file_actions_proto_goTypes = nil
	file_actions_proto_depIdxs = nil
}
