// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: schema.proto

package save

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceType int32

const (
	ResourceType_ResourceWood     ResourceType = 0
	ResourceType_ResourceStone    ResourceType = 1
	ResourceType_ResourceFood     ResourceType = 2
	ResourceType_ResourceIron     ResourceType = 3
	ResourceType_ResourceGold     ResourceType = 4
	ResourceType_ResourceDiamonds ResourceType = 5
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "ResourceWood",
		1: "ResourceStone",
		2: "ResourceFood",
		3: "ResourceIron",
		4: "ResourceGold",
		5: "ResourceDiamonds",
	}
	ResourceType_value = map[string]int32{
		"ResourceWood":     0,
		"ResourceStone":    1,
		"ResourceFood":     2,
		"ResourceIron":     3,
		"ResourceGold":     4,
		"ResourceDiamonds": 5,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

type TerrainType int32

const (
	TerrainType_TerrainPlains    TerrainType = 0
	TerrainType_TerrainForest    TerrainType = 1
	TerrainType_TerrainDesert    TerrainType = 2
	TerrainType_TerrainMountains TerrainType = 3
	TerrainType_TerrainWater     TerrainType = 4
	TerrainType_TerrainShore     TerrainType = 5
)

// Enum value maps for TerrainType.
var (
	TerrainType_name = map[int32]string{
		0: "TerrainPlains",
		1: "TerrainForest",
		2: "TerrainDesert",
		3: "TerrainMountains",
		4: "TerrainWater",
		5: "TerrainShore",
	}
	TerrainType_value = map[string]int32{
		"TerrainPlains":    0,
		"TerrainForest":    1,
		"TerrainDesert":    2,
		"TerrainMountains": 3,
		"TerrainWater":     4,
		"TerrainShore":     5,
	}
)

func (x TerrainType) Enum() *TerrainType {
	p := new(TerrainType)
	*p = x
	return p
}

func (x TerrainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerrainType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[1].Descriptor()
}

func (TerrainType) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[1]
}

func (x TerrainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerrainType.Descriptor instead.
func (TerrainType) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

type DepositType int32

const (
	DepositType_DepositTrees     DepositType = 0
	DepositType_DepositRocks     DepositType = 1
	DepositType_DepositBerries   DepositType = 2
	DepositType_DepositMushrooms DepositType = 3
	DepositType_DepositDeer      DepositType = 4
	DepositType_DepositIronOre   DepositType = 5
)

// Enum value maps for DepositType.
var (
	DepositType_name = map[int32]string{
		0: "DepositTrees",
		1: "DepositRocks",
		2: "DepositBerries",
		3: "DepositMushrooms",
		4: "DepositDeer",
		5: "DepositIronOre",
	}
	DepositType_value = map[string]int32{
		"DepositTrees":     0,
		"DepositRocks":     1,
		"DepositBerries":   2,
		"DepositMushrooms": 3,
		"DepositDeer":      4,
		"DepositIronOre":   5,
	}
)

func (x DepositType) Enum() *DepositType {
	p := new(DepositType)
	*p = x
	return p
}

func (x DepositType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepositType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[2].Descriptor()
}

func (DepositType) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[2]
}

func (x DepositType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepositType.Descriptor instead.
func (DepositType) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

type BuildingType int32

const (
	BuildingType_BuildingSettlement BuildingType = 0
)

// Enum value maps for BuildingType.
var (
	BuildingType_name = map[int32]string{
		0: "BuildingSettlement",
	}
	BuildingType_value = map[string]int32{
		"BuildingSettlement": 0,
	}
)

func (x BuildingType) Enum() *BuildingType {
	p := new(BuildingType)
	*p = x
	return p
}

func (x BuildingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildingType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[3].Descriptor()
}

func (BuildingType) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[3]
}

func (x BuildingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildingType.Descriptor instead.
func (BuildingType) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{3}
}

type TechnologyType int32

const (
	TechnologyType_TechnologyMining      TechnologyType = 0
	TechnologyType_TechnologyStonecraft  TechnologyType = 1
	TechnologyType_TechnologyIronworking TechnologyType = 2
	TechnologyType_TechnologySentryTower TechnologyType = 3
	TechnologyType_TechnologySwords      TechnologyType = 4
	TechnologyType_TechnologyKnighthood  TechnologyType = 5
	TechnologyType_TechnologyGranary     TechnologyType = 6
	TechnologyType_TechnologyHunting     TechnologyType = 7
	TechnologyType_TechnologyFarming     TechnologyType = 8
	TechnologyType_TechnologyCurrency    TechnologyType = 9
	TechnologyType_TechnologyDocks       TechnologyType = 10
	TechnologyType_TechnologyTrade       TechnologyType = 11
)

// Enum value maps for TechnologyType.
var (
	TechnologyType_name = map[int32]string{
		0:  "TechnologyMining",
		1:  "TechnologyStonecraft",
		2:  "TechnologyIronworking",
		3:  "TechnologySentryTower",
		4:  "TechnologySwords",
		5:  "TechnologyKnighthood",
		6:  "TechnologyGranary",
		7:  "TechnologyHunting",
		8:  "TechnologyFarming",
		9:  "TechnologyCurrency",
		10: "TechnologyDocks",
		11: "TechnologyTrade",
	}
	TechnologyType_value = map[string]int32{
		"TechnologyMining":      0,
		"TechnologyStonecraft":  1,
		"TechnologyIronworking": 2,
		"TechnologySentryTower": 3,
		"TechnologySwords":      4,
		"TechnologyKnighthood":  5,
		"TechnologyGranary":     6,
		"TechnologyHunting":     7,
		"TechnologyFarming":     8,
		"TechnologyCurrency":    9,
		"TechnologyDocks":       10,
		"TechnologyTrade":       11,
	}
)

func (x TechnologyType) Enum() *TechnologyType {
	p := new(TechnologyType)
	*p = x
	return p
}

func (x TechnologyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TechnologyType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[4].Descriptor()
}

func (TechnologyType) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[4]
}

func (x TechnologyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TechnologyType.Descriptor instead.
func (TechnologyType) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{4}
}

type SeasonType int32

const (
	SeasonType_SeasonSpring SeasonType = 0
	SeasonType_SeasonSummer SeasonType = 1
	SeasonType_SeasonFall   SeasonType = 2
	SeasonType_SeasonWinter SeasonType = 3
)

// Enum value maps for SeasonType.
var (
	SeasonType_name = map[int32]string{
		0: "SeasonSpring",
		1: "SeasonSummer",
		2: "SeasonFall",
		3: "SeasonWinter",
	}
	SeasonType_value = map[string]int32{
		"SeasonSpring": 0,
		"SeasonSummer": 1,
		"SeasonFall":   2,
		"SeasonWinter": 3,
	}
)

func (x SeasonType) Enum() *SeasonType {
	p := new(SeasonType)
	*p = x
	return p
}

func (x SeasonType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeasonType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[5].Descriptor()
}

func (SeasonType) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[5]
}

func (x SeasonType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeasonType.Descriptor instead.
func (SeasonType) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{5}
}

type PlayerCharacterType int32

const (
	PlayerCharacterType_PlayerCharacterKing     PlayerCharacterType = 0
	PlayerCharacterType_PlayerCharacterQueen    PlayerCharacterType = 1
	PlayerCharacterType_PlayerCharacterPrincess PlayerCharacterType = 2
	PlayerCharacterType_PlayerCharacterMerchant PlayerCharacterType = 3
)

// Enum value maps for PlayerCharacterType.
var (
	PlayerCharacterType_name = map[int32]string{
		0: "PlayerCharacterKing",
		1: "PlayerCharacterQueen",
		2: "PlayerCharacterPrincess",
		3: "PlayerCharacterMerchant",
	}
	PlayerCharacterType_value = map[string]int32{
		"PlayerCharacterKing":     0,
		"PlayerCharacterQueen":    1,
		"PlayerCharacterPrincess": 2,
		"PlayerCharacterMerchant": 3,
	}
)

func (x PlayerCharacterType) Enum() *PlayerCharacterType {
	p := new(PlayerCharacterType)
	*p = x
	return p
}

func (x PlayerCharacterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerCharacterType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_proto_enumTypes[6].Descriptor()
}

func (PlayerCharacterType) Type() protoreflect.EnumType {
	return &file_schema_proto_enumTypes[6]
}

func (x PlayerCharacterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerCharacterType.Descriptor instead.
func (PlayerCharacterType) EnumDescriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{6}
}

type Global struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Diamonds int64   `protobuf:"varint,2,opt,name=diamonds,proto3" json:"diamonds,omitempty"`
}

func (x *Global) Reset() {
	*x = Global{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Global) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Global) ProtoMessage() {}

func (x *Global) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Global.ProtoReflect.Descriptor instead.
func (*Global) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{0}
}

func (x *Global) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Global) GetDiamonds() int64 {
	if x != nil {
		return x.Diamonds
	}
	return 0
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Header     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Board     *Board      `protobuf:"bytes,2,opt,name=board,proto3" json:"board,omitempty"`
	Resources *Resources  `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	Camera    *Camera     `protobuf:"bytes,4,opt,name=camera,proto3" json:"camera,omitempty"`
	Buildings []*Building `protobuf:"bytes,5,rep,name=buildings,proto3" json:"buildings,omitempty"`
	Roads     []*Road     `protobuf:"bytes,6,rep,name=roads,proto3" json:"roads,omitempty"`
	Research  *Research   `protobuf:"bytes,7,opt,name=research,proto3" json:"research,omitempty"`
	Player    *Player     `protobuf:"bytes,8,opt,name=player,proto3" json:"player,omitempty"`
	Progress  *Progress   `protobuf:"bytes,9,opt,name=progress,proto3" json:"progress,omitempty"`
}

func (x *Game) Reset() {
	*x = Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{2}
}

func (x *Game) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Game) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *Game) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Game) GetCamera() *Camera {
	if x != nil {
		return x.Camera
	}
	return nil
}

func (x *Game) GetBuildings() []*Building {
	if x != nil {
		return x.Buildings
	}
	return nil
}

func (x *Game) GetRoads() []*Road {
	if x != nil {
		return x.Roads
	}
	return nil
}

func (x *Game) GetResearch() *Research {
	if x != nil {
		return x.Research
	}
	return nil
}

func (x *Game) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *Game) GetProgress() *Progress {
	if x != nil {
		return x.Progress
	}
	return nil
}

type Board struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width         int64     `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int64     `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Tiles         []*Tile   `protobuf:"bytes,3,rep,name=tiles,proto3" json:"tiles,omitempty"`
	StartPosition *Position `protobuf:"bytes,4,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"`
}

func (x *Board) Reset() {
	*x = Board{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{3}
}

func (x *Board) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Board) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Board) GetTiles() []*Tile {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *Board) GetStartPosition() *Position {
	if x != nil {
		return x.StartPosition
	}
	return nil
}

type Camera struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Vector `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Zoom     *Vector `protobuf:"bytes,2,opt,name=zoom,proto3" json:"zoom,omitempty"`
}

func (x *Camera) Reset() {
	*x = Camera{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Camera) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Camera) ProtoMessage() {}

func (x *Camera) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Camera.ProtoReflect.Descriptor instead.
func (*Camera) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{4}
}

func (x *Camera) GetPosition() *Vector {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Camera) GetZoom() *Vector {
	if x != nil {
		return x.Zoom
	}
	return nil
}

type Research struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Technologies []TechnologyType `protobuf:"varint,2,rep,packed,name=technologies,proto3,enum=save.TechnologyType" json:"technologies,omitempty"`
}

func (x *Research) Reset() {
	*x = Research{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Research) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Research) ProtoMessage() {}

func (x *Research) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Research.ProtoReflect.Descriptor instead.
func (*Research) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{5}
}

func (x *Research) GetTechnologies() []TechnologyType {
	if x != nil {
		return x.Technologies
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Character PlayerCharacterType `protobuf:"varint,1,opt,name=character,proto3,enum=save.PlayerCharacterType" json:"character,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{6}
}

func (x *Player) GetCharacter() PlayerCharacterType {
	if x != nil {
		return x.Character
	}
	return PlayerCharacterType_PlayerCharacterKing
}

type Resources struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wood  int64 `protobuf:"varint,1,opt,name=wood,proto3" json:"wood,omitempty"`
	Stone int64 `protobuf:"varint,2,opt,name=stone,proto3" json:"stone,omitempty"`
	Food  int64 `protobuf:"varint,3,opt,name=food,proto3" json:"food,omitempty"`
	Iron  int64 `protobuf:"varint,4,opt,name=iron,proto3" json:"iron,omitempty"`
	Gold  int64 `protobuf:"varint,5,opt,name=gold,proto3" json:"gold,omitempty"`
}

func (x *Resources) Reset() {
	*x = Resources{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{7}
}

func (x *Resources) GetWood() int64 {
	if x != nil {
		return x.Wood
	}
	return 0
}

func (x *Resources) GetStone() int64 {
	if x != nil {
		return x.Stone
	}
	return 0
}

func (x *Resources) GetFood() int64 {
	if x != nil {
		return x.Food
	}
	return 0
}

func (x *Resources) GetIron() int64 {
	if x != nil {
		return x.Iron
	}
	return 0
}

func (x *Resources) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

type Tile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position     `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Terrain  TerrainType   `protobuf:"varint,2,opt,name=terrain,proto3,enum=save.TerrainType" json:"terrain,omitempty"`
	Deposit  *DepositType  `protobuf:"varint,3,opt,name=deposit,proto3,enum=save.DepositType,oneof" json:"deposit,omitempty"`
	Resource *TileResource `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *Tile) Reset() {
	*x = Tile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{8}
}

func (x *Tile) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Tile) GetTerrain() TerrainType {
	if x != nil {
		return x.Terrain
	}
	return TerrainType_TerrainPlains
}

func (x *Tile) GetDeposit() DepositType {
	if x != nil && x.Deposit != nil {
		return *x.Deposit
	}
	return DepositType_DepositTrees
}

func (x *Tile) GetResource() *TileResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type Building struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position *Position    `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Type     BuildingType `protobuf:"varint,3,opt,name=type,proto3,enum=save.BuildingType" json:"type,omitempty"`
	Level    int64        `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *Building) Reset() {
	*x = Building{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Building) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Building) ProtoMessage() {}

func (x *Building) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Building.ProtoReflect.Descriptor instead.
func (*Building) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{9}
}

func (x *Building) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Building) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Building) GetType() BuildingType {
	if x != nil {
		return x.Type
	}
	return BuildingType_BuildingSettlement
}

func (x *Building) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

type Road struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *Road) Reset() {
	*x = Road{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Road) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Road) ProtoMessage() {}

func (x *Road) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Road.ProtoReflect.Descriptor instead.
func (*Road) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{10}
}

func (x *Road) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Progress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Season SeasonType `protobuf:"varint,1,opt,name=season,proto3,enum=save.SeasonType" json:"season,omitempty"`
	Year   int64      `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Day    int64      `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *Progress) Reset() {
	*x = Progress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{11}
}

func (x *Progress) GetSeason() SeasonType {
	if x != nil {
		return x.Season
	}
	return SeasonType_SeasonSpring
}

func (x *Progress) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Progress) GetDay() int64 {
	if x != nil {
		return x.Day
	}
	return 0
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int64 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{12}
}

func (x *Position) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Vector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vector) Reset() {
	*x = Vector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{13}
}

func (x *Vector) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type TileResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource  ResourceType `protobuf:"varint,1,opt,name=Resource,proto3,enum=save.ResourceType" json:"Resource,omitempty"`
	Amount    int64        `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	MaxAmount int64        `protobuf:"varint,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
}

func (x *TileResource) Reset() {
	*x = TileResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TileResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TileResource) ProtoMessage() {}

func (x *TileResource) ProtoReflect() protoreflect.Message {
	mi := &file_schema_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TileResource.ProtoReflect.Descriptor instead.
func (*TileResource) Descriptor() ([]byte, []int) {
	return file_schema_proto_rawDescGZIP(), []int{14}
}

func (x *TileResource) GetResource() ResourceType {
	if x != nil {
		return x.Resource
	}
	return ResourceType_ResourceWood
}

func (x *TileResource) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TileResource) GetMaxAmount() int64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

var File_schema_proto protoreflect.FileDescriptor

var file_schema_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x73, 0x61, 0x76, 0x65, 0x22, 0x4a, 0x0a, 0x06, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x12, 0x24,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x73,
	0x22, 0x22, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0xf2, 0x02, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x73, 0x61, 0x76, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52,
	0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x61, 0x76, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x43, 0x61, 0x6d,
	0x65, 0x72, 0x61, 0x52, 0x06, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x2c, 0x0a, 0x09, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x09,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x72, 0x6f, 0x61,
	0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e,
	0x52, 0x6f, 0x61, 0x64, 0x52, 0x05, 0x72, 0x6f, 0x61, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x73, 0x61, 0x76, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x24, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x2a, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x22, 0x8e, 0x01, 0x0a, 0x05, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x74, 0x69,
	0x6c, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x61,
	0x76, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x54, 0x0a, 0x06, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x0a, 0x04, 0x7a, 0x6f, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73,
	0x61, 0x76, 0x65, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x04, 0x7a, 0x6f, 0x6f, 0x6d,
	0x22, 0x44, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x38, 0x0a, 0x0c,
	0x74, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x6f,
	0x6c, 0x6f, 0x67, 0x69, 0x65, 0x73, 0x22, 0x41, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x37, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09,
	0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x22, 0x71, 0x0a, 0x09, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x6f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x77, 0x6f, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x74, 0x6f, 0x6e, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x66, 0x6f, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x72, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x69, 0x72, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x22, 0xcd, 0x01, 0x0a,
	0x04, 0x54, 0x69, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2b, 0x0a, 0x07, 0x74, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x11, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x54, 0x65, 0x72, 0x72, 0x61, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x74, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x12, 0x30,
	0x0a, 0x07, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x22, 0x84, 0x01, 0x0a,
	0x08, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x61,
	0x76, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x22, 0x32, 0x0a, 0x04, 0x52, 0x6f, 0x61, 0x64, 0x12, 0x2a, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x73, 0x61, 0x76, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x79, 0x65, 0x61,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x64, 0x61, 0x79, 0x22, 0x26, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x79, 0x22, 0x24, 0x0a, 0x06, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x79, 0x22, 0x75, 0x0a, 0x0c, 0x54, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x2e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x78,
	0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d,
	0x61, 0x78, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2a, 0x7f, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x57, 0x6f, 0x6f, 0x64, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x6e, 0x65, 0x10, 0x01, 0x12, 0x10, 0x0a,
	0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x72, 0x6f, 0x6e, 0x10,
	0x03, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x47, 0x6f, 0x6c,
	0x64, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44,
	0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x73, 0x10, 0x05, 0x2a, 0x80, 0x01, 0x0a, 0x0b, 0x54, 0x65,
	0x72, 0x72, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x65, 0x72,
	0x72, 0x61, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x73, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d,
	0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x46, 0x6f, 0x72, 0x65, 0x73, 0x74, 0x10, 0x01, 0x12,
	0x11, 0x0a, 0x0d, 0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x44, 0x65, 0x73, 0x65, 0x72, 0x74,
	0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x65, 0x72, 0x72, 0x61, 0x69, 0x6e, 0x4d, 0x6f, 0x75,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x73, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x65, 0x72, 0x72,
	0x61, 0x69, 0x6e, 0x57, 0x61, 0x74, 0x65, 0x72, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x65,
	0x72, 0x72, 0x61, 0x69, 0x6e, 0x53, 0x68, 0x6f, 0x72, 0x65, 0x10, 0x05, 0x2a, 0x80, 0x01, 0x0a,
	0x0b, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c,
	0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x54, 0x72, 0x65, 0x65, 0x73, 0x10, 0x00, 0x12, 0x10,
	0x0a, 0x0c, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x52, 0x6f, 0x63, 0x6b, 0x73, 0x10, 0x01,
	0x12, 0x12, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x42, 0x65, 0x72, 0x72, 0x69,
	0x65, 0x73, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4d,
	0x75, 0x73, 0x68, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x44, 0x65, 0x65, 0x72, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x49, 0x72, 0x6f, 0x6e, 0x4f, 0x72, 0x65, 0x10, 0x05, 0x2a,
	0x26, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x12, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x74, 0x74, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x00, 0x2a, 0xad, 0x02, 0x0a, 0x0e, 0x54, 0x65, 0x63, 0x68,
	0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x65,
	0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4d, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x10, 0x00,
	0x12, 0x18, 0x0a, 0x14, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x53, 0x74,
	0x6f, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x65,
	0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x49, 0x72, 0x6f, 0x6e, 0x77, 0x6f, 0x72, 0x6b,
	0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x53, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x10, 0x03,
	0x12, 0x14, 0x0a, 0x10, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x53, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x10, 0x04, 0x12, 0x18, 0x0a, 0x14, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x4b, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x68, 0x6f, 0x6f, 0x64, 0x10, 0x05,
	0x12, 0x15, 0x0a, 0x11, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x47, 0x72,
	0x61, 0x6e, 0x61, 0x72, 0x79, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x54, 0x65, 0x63, 0x68, 0x6e,
	0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x48, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x07, 0x12, 0x15,
	0x0a, 0x11, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x46, 0x61, 0x72, 0x6d,
	0x69, 0x6e, 0x67, 0x10, 0x08, 0x12, 0x16, 0x0a, 0x12, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x10, 0x09, 0x12, 0x13, 0x0a,
	0x0f, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x44, 0x6f, 0x63, 0x6b, 0x73,
	0x10, 0x0a, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79,
	0x54, 0x72, 0x61, 0x64, 0x65, 0x10, 0x0b, 0x2a, 0x52, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x53,
	0x70, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x53, 0x75, 0x6d, 0x6d, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x46, 0x61, 0x6c, 0x6c, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x57, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x10, 0x03, 0x2a, 0x82, 0x01, 0x0a, 0x13,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4b, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x51,
	0x75, 0x65, 0x65, 0x6e, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x65, 0x73,
	0x73, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x10, 0x03,
	0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d,
	0x31, 0x31, 0x30, 0x2f, 0x6b, 0x69, 0x6e, 0x67, 0x64, 0x6f, 0x6d, 0x73, 0x2f, 0x73, 0x61, 0x76,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_proto_rawDescOnce sync.Once
	file_schema_proto_rawDescData = file_schema_proto_rawDesc
)

func file_schema_proto_rawDescGZIP() []byte {
	file_schema_proto_rawDescOnce.Do(func() {
		file_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_proto_rawDescData)
	})
	return file_schema_proto_rawDescData
}

var file_schema_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_schema_proto_goTypes = []interface{}{
	(ResourceType)(0),        // 0: save.ResourceType
	(TerrainType)(0),         // 1: save.TerrainType
	(DepositType)(0),         // 2: save.DepositType
	(BuildingType)(0),        // 3: save.BuildingType
	(TechnologyType)(0),      // 4: save.TechnologyType
	(SeasonType)(0),          // 5: save.SeasonType
	(PlayerCharacterType)(0), // 6: save.PlayerCharacterType
	(*Global)(nil),           // 7: save.Global
	(*Header)(nil),           // 8: save.Header
	(*Game)(nil),             // 9: save.Game
	(*Board)(nil),            // 10: save.Board
	(*Camera)(nil),           // 11: save.Camera
	(*Research)(nil),         // 12: save.Research
	(*Player)(nil),           // 13: save.Player
	(*Resources)(nil),        // 14: save.Resources
	(*Tile)(nil),             // 15: save.Tile
	(*Building)(nil),         // 16: save.Building
	(*Road)(nil),             // 17: save.Road
	(*Progress)(nil),         // 18: save.Progress
	(*Position)(nil),         // 19: save.Position
	(*Vector)(nil),           // 20: save.Vector
	(*TileResource)(nil),     // 21: save.TileResource
}
var file_schema_proto_depIdxs = []int32{
	8,  // 0: save.Global.header:type_name -> save.Header
	8,  // 1: save.Game.header:type_name -> save.Header
	10, // 2: save.Game.board:type_name -> save.Board
	14, // 3: save.Game.resources:type_name -> save.Resources
	11, // 4: save.Game.camera:type_name -> save.Camera
	16, // 5: save.Game.buildings:type_name -> save.Building
	17, // 6: save.Game.roads:type_name -> save.Road
	12, // 7: save.Game.research:type_name -> save.Research
	13, // 8: save.Game.player:type_name -> save.Player
	18, // 9: save.Game.progress:type_name -> save.Progress
	15, // 10: save.Board.tiles:type_name -> save.Tile
	19, // 11: save.Board.start_position:type_name -> save.Position
	20, // 12: save.Camera.position:type_name -> save.Vector
	20, // 13: save.Camera.zoom:type_name -> save.Vector
	4,  // 14: save.Research.technologies:type_name -> save.TechnologyType
	6,  // 15: save.Player.character:type_name -> save.PlayerCharacterType
	19, // 16: save.Tile.position:type_name -> save.Position
	1,  // 17: save.Tile.terrain:type_name -> save.TerrainType
	2,  // 18: save.Tile.deposit:type_name -> save.DepositType
	21, // 19: save.Tile.resource:type_name -> save.TileResource
	19, // 20: save.Building.position:type_name -> save.Position
	3,  // 21: save.Building.type:type_name -> save.BuildingType
	19, // 22: save.Road.position:type_name -> save.Position
	5,  // 23: save.Progress.season:type_name -> save.SeasonType
	0,  // 24: save.TileResource.Resource:type_name -> save.ResourceType
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_schema_proto_init() }
func file_schema_proto_init() {
	if File_schema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Global); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Board); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Camera); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Research); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resources); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Building); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Road); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Progress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TileResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_schema_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_proto_rawDesc,
			NumEnums:      7,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_proto_goTypes,
		DependencyIndexes: file_schema_proto_depIdxs,
		EnumInfos:         file_schema_proto_enumTypes,
		MessageInfos:      file_schema_proto_msgTypes,
	}.Build()
	File_schema_proto = out.File
	file_schema_proto_rawDesc = nil
	file_schema_proto_goTypes = nil
	file_schema_proto_depIdxs = nil
}
